overrides:
  '@injectivelabs/networks': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/networks
  '@injectivelabs/sdk-ts': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/sdk-ts
  '@injectivelabs/ts-types': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/ts-types
  '@injectivelabs/utils': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/utils
  '@injectivelabs/wallet-base': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-base
  '@injectivelabs/wallet-core': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-core
  '@injectivelabs/wallet-cosmos': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-cosmos
  '@injectivelabs/wallet-cosmos-strategy': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-cosmos-strategy
  '@injectivelabs/wallet-cosmostation': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-cosmostation
  '@injectivelabs/wallet-evm': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-evm
  '@injectivelabs/wallet-ledger': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-ledger
  '@injectivelabs/wallet-magic': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-magic
  '@injectivelabs/wallet-private-key': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-private-key
  '@injectivelabs/wallet-strategy': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-strategy
  '@injectivelabs/wallet-trezor': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-trezor
  '@injectivelabs/wallet-wallet-connect': link:../../../../.pnpm-global/5/node_modules/@injectivelabs/wallet-wallet-connect
  '@solana/web3.js': 1.98.0
  bignumber.js: 9.1.2
  crypto-js: 4.2.0
  rpc-websockets: 9.0.4
