// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconsClose: typeof import('./lib/components/icons/Close.vue')['default']
    IconsError: typeof import('./lib/components/icons/Error.vue')['default']
    IconsSuccess: typeof import('./lib/components/icons/Success.vue')['default']
    IconsWarning: typeof import('./lib/components/icons/Warning.vue')['default']
    Notification: typeof import('./lib/components/Notification.vue')['default']
    Notifications: typeof import('./lib/components/Notifications.vue')['default']
    NotificationWrapper: typeof import('./lib/components/NotificationWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
