// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dropdown: typeof import('./lib/components/Dropdown.vue')['default']
    DropdownItem: typeof import('./lib/components/DropdownItem.vue')['default']
    HoverMenu: typeof import('./lib/components/HoverMenu.vue')['default']
    Icon: typeof import('./lib/components/Icon.vue')['default']
    Input: typeof import('./lib/components/Input.vue')['default']
    ModalWrapper: typeof import('./lib/components/ModalWrapper.vue')['default']
    NumericInput: typeof import('./lib/components/NumericInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectorItem: typeof import('./lib/components/SelectorItem.vue')['default']
    SortableHeaderItem: typeof import('./lib/components/SortableHeaderItem.vue')['default']
    Spinner: typeof import('./lib/components/Spinner.vue')['default']
    TextArea: typeof import('./lib/components/TextArea.vue')['default']
  }
}
