/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BitMapFilterList: typeof import('./lib/components/BitMapFilterList.vue')['default']
    Checkbox: typeof import('./lib/components/Checkbox.vue')['default']
    Datepicker: typeof import('./lib/components/Datepicker.vue')['default']
    Dropdown: typeof import('./lib/components/Dropdown.vue')['default']
    DropdownItem: typeof import('./lib/components/DropdownItem.vue')['default']
    HoverMenu: typeof import('./lib/components/HoverMenu.vue')['default']
    Icon: typeof import('./lib/components/Icon.vue')['default']
    Input: typeof import('./lib/components/Input.vue')['default']
    LineGraph: typeof import('./lib/components/LineGraph.vue')['default']
    ModalWrapper: typeof import('./lib/components/ModalWrapper.vue')['default']
    MultiSelect: typeof import('./lib/components/MultiSelect.vue')['default']
    Notification: typeof import('./lib/components/Notification.vue')['default']
    Notifications: typeof import('./lib/components/Notifications.vue')['default']
    NotificationWrapper: typeof import('./lib/components/NotificationWrapper.vue')['default']
    NumericInput: typeof import('./lib/components/NumericInput.vue')['default']
    PaginationWrapper: typeof import('./lib/components/PaginationWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectorItem: typeof import('./lib/components/SelectorItem.vue')['default']
    SortableHeaderItem: typeof import('./lib/components/SortableHeaderItem.vue')['default']
    Spinner: typeof import('./lib/components/Spinner.vue')['default']
    TextArea: typeof import('./lib/components/TextArea.vue')['default']
  }
}
