import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import process from 'node:process'

import { parse as parseYaml } from 'yaml'

type OpenApiInfo = {
  title: string
  version: string
}

type OpenApiSpec = {
  openapi: string
  info: OpenApiInfo
  paths: Record<string, OpenApiPathItem>
} & Record<string, unknown>

const VERBOSE = process.env.VERBOSE === '1'

function logVerbose(...args: unknown[]) {
  if (VERBOSE) {
    console.log('[gen-bff-client]', ...args)
  }
}

const BFF_OUTPUT_FILE_PATH = path.resolve(
  process.cwd(),
  'app/generated/bff-api-types.ts'
)

type HttpMethod =
  | 'get'
  | 'put'
  | 'post'
  | 'delete'
  | 'options'
  | 'head'
  | 'patch'
  | 'trace'

const HTTP_METHODS: ReadonlyArray<HttpMethod> = [
  'get',
  'put',
  'post',
  'delete',
  'options',
  'head',
  'patch',
  'trace'
]

type TreeOperation = {
  method: HttpMethod
  path: string
}

type TreeNode = {
  children: Record<string, TreeNode>
  operations: Array<TreeOperation>
}

type OpenApiPathItem = Partial<Record<HttpMethod, unknown>> &
  Record<string, unknown>

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null
}

function createNode(): TreeNode {
  return {
    children: {},
    operations: []
  }
}

function escapeStringValue(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
}

function sanitizePathSegment(segment: string): string {
  const dynamicMatch = segment.match(/^\{(.+)\}$/)
  const normalizedSegment = dynamicMatch ? `$${dynamicMatch[1]}` : segment

  const withoutInvalidChars = normalizedSegment.replace(/[^A-Za-z0-9_$]/g, '_')
  const withValidStart = /^[A-Za-z_$]/.test(withoutInvalidChars)
    ? withoutInvalidChars
    : `_${withoutInvalidChars}`

  return withValidStart
}

function addPathOperation(
  root: TreeNode,
  openApiPath: string,
  method: HttpMethod
): void {
  const segments = openApiPath.split('/').filter(Boolean)
  let currentNode = root

  for (const segment of segments) {
    const childKey = sanitizePathSegment(segment)

    if (!currentNode.children[childKey]) {
      currentNode.children[childKey] = createNode()
    }

    currentNode = currentNode.children[childKey]
  }

  currentNode.operations.push({
    method,
    path: openApiPath
  })
}

function buildPathTree(paths: Record<string, OpenApiPathItem>): TreeNode {
  const root = createNode()

  for (const [openApiPath, pathItem] of Object.entries(paths)) {
    if (!isRecord(pathItem)) {
      continue
    }

    for (const method of HTTP_METHODS) {
      if (pathItem[method]) {
        addPathOperation(root, openApiPath, method)
      }
    }
  }

  return root
}

function sortNode(node: TreeNode): TreeNode {
  for (const child of Object.values(node.children)) {
    sortNode(child)
  }

  node.children = Object.fromEntries(
    Object.entries(node.children).sort(([keyA], [keyB]) =>
      keyA.localeCompare(keyB)
    )
  )

  node.operations.sort((operationA, operationB) => {
    const methodIndexA = HTTP_METHODS.indexOf(operationA.method)
    const methodIndexB = HTTP_METHODS.indexOf(operationB.method)

    return methodIndexA - methodIndexB
  })

  return node
}

function renderNode(node: TreeNode, depth = 1): Array<string> {
  const indentation = '  '.repeat(depth)
  const lines: Array<string> = []

  for (const [childKey, childNode] of Object.entries(node.children)) {
    lines.push(`${indentation}${childKey}: {`)
    lines.push(...renderNode(childNode, depth + 1))
    lines.push(`${indentation}},`)
  }

  for (const operation of node.operations) {
    const clientMethod = operation.method.toUpperCase() as Uppercase<HttpMethod>
    const escapedPath = escapeStringValue(operation.path)

    lines.push(
      `${indentation}${operation.method}: ((...init: MethodArgs<'${operation.method}', '${escapedPath}'>) =>`
    )
    lines.push(
      `${indentation}  client.${clientMethod}('${escapedPath}', ...init)) as LeafMethod<'${operation.method}', '${escapedPath}'>,`
    )
  }

  return lines
}

function renderBffClient(pathTree: TreeNode): string {
  const lines = [
    '// This file is auto-generated by scripts/gen-bff-client.ts',
    '',
    "import type { FilterKeys, HttpMethod, MediaType, PathsWithMethod, RequiredKeysOf } from 'openapi-typescript-helpers'",
    "import type { Client, FetchOptions, FetchResponse } from 'openapi-fetch'",
    '',
    "import type { paths } from './bff.generated'",
    '',
    'type ApiClient = Client<paths, MediaType>',
    '',
    'type MethodInit<',
    '  TMethod extends HttpMethod,',
    '  TPath extends PathsWithMethod<paths, TMethod>,',
    '> = FetchOptions<FilterKeys<paths[TPath], TMethod>>',
    '',
    'type MethodArgs<',
    '  TMethod extends HttpMethod,',
    '  TPath extends PathsWithMethod<paths, TMethod>,',
    '> = RequiredKeysOf<MethodInit<TMethod, TPath>> extends never',
    '  ? [MethodInit<TMethod, TPath>?]',
    '  : [MethodInit<TMethod, TPath>]',
    '',
    'type MethodResult<',
    '  TMethod extends HttpMethod,',
    '  TPath extends PathsWithMethod<paths, TMethod>,',
<<<<<<< HEAD
<<<<<<< HEAD
    '> = FetchResponse<NonNullable<paths[TPath][TMethod]>, MethodInit<TMethod, TPath>, MediaType>',
=======
    '> = FetchResponse<paths[TPath][TMethod], MethodInit<TMethod, TPath>, MediaType>',
>>>>>>> c7b2b0b (feat: setup bff markets endpoint)
=======
    '> = FetchResponse<NonNullable<paths[TPath][TMethod]>, MethodInit<TMethod, TPath>, MediaType>',
>>>>>>> f776d78 (fix: bff typing errors)
    '',
    'export type LeafMethod<',
    '  TMethod extends HttpMethod,',
    '  TPath extends PathsWithMethod<paths, TMethod>,',
    '> = ((...init: MethodArgs<TMethod, TPath>) => Promise<MethodResult<TMethod, TPath>>) & {',
    '  readonly __method: TMethod',
    '  readonly __path: TPath',
    '}',
    '',
    'export function createBffClient(client: ApiClient) {',
    '  return {',
    ...renderNode(pathTree, 2),
    '  }',
    '}',
    '',
    'export type BffClient = ReturnType<typeof createBffClient>',
    ''
  ]

  return lines.join('\n')
}

function validateStringField(
  value: unknown,
  fieldName: string,
  source: string
): string {
  if (!value || typeof value !== 'string') {
    throw new Error(
      `Invalid OpenAPI spec from ${source}: missing or invalid '${fieldName}' field`
    )
  }
  return value
}

function validateOpenApiSpec(spec: unknown, source: string): OpenApiSpec {
  if (!isRecord(spec)) {
    throw new Error(`Invalid OpenAPI spec from ${source}: not an object`)
  }

  validateStringField(spec.openapi, 'openapi', source)

  if (!isRecord(spec.info)) {
    throw new Error(
      `Invalid OpenAPI spec from ${source}: 'info' must be an object`
    )
  }

  const title = validateStringField(spec.info.title, 'info.title', source)
  const version = validateStringField(spec.info.version, 'info.version', source)

  if (!isRecord(spec.paths)) {
    throw new Error(
      `Invalid OpenAPI spec from ${source}: 'paths' must be an object`
    )
  }

  const pathCount = Object.keys(spec.paths).length
  logVerbose(`Validated OpenAPI spec: ${title} v${version}, ${pathCount} paths`)

  return spec as OpenApiSpec
}

async function loadSpec(specPath: string): Promise<OpenApiSpec> {
  const absoluteSpecPath = path.resolve(process.cwd(), specPath)
  const specContents = await readFile(absoluteSpecPath, 'utf8')
  logVerbose(`Read OpenAPI spec from ${absoluteSpecPath}`)

  const extension = path.extname(specPath).toLowerCase()

  let spec: unknown
  if (extension === '.yaml' || extension === '.yml') {
    spec = parseYaml(specContents)
  } else {
    try {
      spec = JSON.parse(specContents)
    } catch {
      spec = parseYaml(specContents)
    }
  }

  return validateOpenApiSpec(spec, absoluteSpecPath)
}

async function main() {
  const specPath = process.env.SPEC_PATH

  if (!specPath) {
    console.error('Error: SPEC_PATH environment variable is required')
    console.error(
      'Usage: SPEC_PATH=path/to/spec.json node scripts/gen-bff-client.ts'
    )
    process.exit(1)
  }

  const spec = await loadSpec(specPath)

  const pathTree = sortNode(buildPathTree(spec.paths))

  logVerbose('Building BFF client type definitions...')
  const bffClientSource = renderBffClient(pathTree)

  await mkdir(path.dirname(BFF_OUTPUT_FILE_PATH), { recursive: true })
  await writeFile(BFF_OUTPUT_FILE_PATH, bffClientSource)

  console.log(`Generated ${BFF_OUTPUT_FILE_PATH}`)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exit(1)
})
