// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HoverMenu: typeof import('./lib/components/HoverMenu.vue')['default']
    Icon: typeof import('./lib/components/Icon.vue')['default']
    IconHub: typeof import('./lib/components/IconHub.vue')['default']
    Input: typeof import('./lib/components/Input.vue')['default']
    ModalWrapper: typeof import('./lib/components/ModalWrapper.vue')['default']
    NumericInput: typeof import('./lib/components/NumericInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selector: typeof import('./lib/components/Selector.vue')['default']
    SelectorItem: typeof import('./lib/components/SelectorItem.vue')['default']
    Spinner: typeof import('./lib/components/Spinner.vue')['default']
    Textarea: typeof import('./assets/components/Textarea.vue')['default']
    TextArea: typeof import('./lib/components/TextArea.vue')['default']
  }
}
